services:
    mysql:
        container_name: mysql_mysite_container_41494
        image: mysql:latest
        working_dir: /app
        command: 
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
        restart: always
        ports:
            - "41494:3306"
        environment:
            - MYSQL_DATABASE=mysite
            - MYSQL_ROOT_PASSWORD=mysite
            - MYSQL_USER=mysite
            - MYSQL_PASSWORD=mysite
        volumes:
            - "mysql_mysite_volume_41494:/var/lib/mysql"

volumes:
    mysql_mysite_volume_41494:
