# Generated by Django 5.1.1 on 2024-10-03 07:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcategory_options_blogpagecategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('content', 0), ('image', 1), ('quote', 2), ('twitter_block', 4)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'h1', 'h2', 'h3'], 'template': 'blocks/richtext.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blocks/image.html'}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {'template': 'blocks/quote.html'}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('text', 3), ('author', 3)]], {'template': 'blocks/twitter_block.html'})}),
        ),
    ]
