# Generated by Django 5.1.1 on 2024-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('grey', 'Grey'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('lime', 'Lime'), ('amber', 'Amber')], default='grey', help_text='Background color', max_length=6),
        ),
    ]
