# Generated by Django 5.1.1 on 2024-10-03 16:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('content', 0), ('image', 1), ('quote', 2), ('twitter_block', 4), ('code', 7), ('result', 8)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'h1', 'h2', 'h3'], 'template': 'blocks/richtext.html'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blocks/image.html'}), 2: ('wagtail.blocks.BlockQuoteBlock', (), {'template': 'blocks/quote.html'}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('text', 3), ('author', 3)]], {'template': 'blocks/twitter_block.html'}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('shell', 'Shell')], 'label': 'Langue du Code'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Code Source'}), 7: ('wagtail.blocks.StructBlock', [[('language', 5), ('code', 6)]], {}), 8: ('blog.models.ResultBlock', (), {})}),
        ),
    ]
