# Generated by Django 5.1.1 on 2024-10-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projectpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
