# Generated by Django 5.1.1 on 2024-10-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_brandsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlinks',
            name='codepen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footerlinks',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
