# Generated by Django 5.1.1 on 2024-10-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_experiencepage_date_in_experiencepage_date_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencepage',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
