# Generated by Django 5.1.1 on 2024-10-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('grey', 'Grey'), ('red', 'Red'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink'), ('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('lime', 'Lime'), ('amber', 'Amber')], default='grey', help_text='Background color', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
